name: Build & push API image to ACR and recreate AKS

on:
  workflow_dispatch:
  
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  ACR_REGISTRY: acrrepository.azurecr.io

jobs:
  docker_build_and_push:
    name: AKS deploy after build and push API image to ACR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with: 
            ref: master

      - name: Setup .Net
        uses: actions/setup-dotnet@v2
        with:
            dotnet-version: 7.0.x

      - name: Generate Image Tag
        id: generate_image_tag
        run: |
          CURRENT_DATE=$(date +'%Y%m%d')
          ORDER_NUMBER=$((GITHUB_RUN_NUMBER))
          IMAGE_TAG="${CURRENT_DATE}-v${ORDER_NUMBER}"
          echo "::set-output name=IMAGE_TAG::$IMAGE_TAG"

      - name: Docker Login
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin $ACR_REGISTRY
            
      - name: Build and Push Docker image
        run: |
          docker pull nginx:latest
          docker tag nginx:latest acrrepository.azurecr.io/dashboard:$IMAGE_TAG
          docker push acrrepository.azurecr.io/dashboard:$IMAGE_T
