name: Build & push API image to ACR and recreate AKS

on:
  workflow_dispatch:
  
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  ACR_REGISTRY: acrrepository.azurecr.io

jobs:
  docker_build_and_push:
    name: AKS deploy after build and push api image to ACR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with: 
            ref: master

      - name: Setup .Net
        uses: actions/setup-dotnet@v2
        with:
            dotnet-version: 7.0.x

      - name: Set Image Tag
        run: |
          CURRENT_DATE=$(date +'%Y%m%d')
          MAJOR_VERSION="10"               
          MINOR_VERSION=$((GITHUB_RUN_NUMBER / 1000)) 
          PATCH_VERSION=$((GITHUB_RUN_NUMBER % 1000)) 
      
          CLEAN_DATE=$(echo $CURRENT_DATE | tr -d ':')

          IMAGE_TAG="${CLEAN_DATE}-v${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}"

      - name: Docker Login
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $ACR_REGISTRY

      - name: Build and Push Docker image
        run: |
          docker pull nginx:latest
          docker tag nginx:latest acrrepository.azurecr.io/dashboard:$IMAGE_TAG
          docker push acrrepository.azurecr.io/dashboard:$IMAGE_TAG

