name: Build & push API image to ACR and recreate AKS

on:
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  ACR_REGISTRY: acrrepository.azurecr.io

jobs:
  docker_build_and_push:
    name: AKS deploy after build and push api image to ACR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with: 
            ref: master

      - name: Setup .Net
        uses: actions/setup-dotnet@v2
        with:
            dotnet-version: 7.0.x

      - name: Generate Image Tag
        id: generate_image_tag
        run: |
          CURRENT_DATE=$(date +'%Y%m%d')
          ORDER_NUMBER=$((GITHUB_RUN_NUMBER))
          IMAGE_TAG="${CURRENT_DATE}-v${ORDER_NUMBER}"
          echo "::set-output name=IMAGE_TAG::$IMAGE_TAG"

      - name: Log Image Tag
        run: echo "Generated Image Tag: ${{ steps.generate_image_tag.outputs.IMAGE_TAG }}"

      - name: Docker Login
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $ACR_REGISTRY
            
      - name: Docker Compose Build 
        run: docker-compose build
        
      - name: Tag and Push Image
        run: |
          docker tag znode10xapiimage:${{ steps.generate_image_tag.outputs.IMAGE_TAG }} $ACR_REGISTRY/znode10xapiimage:${{ steps.generate_image_tag.outputs.IMAGE_TAG }}
          docker push $ACR_REGISTRY/znode10xapiimage:${{ steps.generate_image_tag.outputs.IMAGE_TAG }}
         
      - name: Docker Logout
        if: always()
        continue-on-error: true
        run: docker logout $ACR_REGISTRY
