jobs:
  production:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        run: docker login -u acrrepository -p D87PyhU8ipAeLEUolrwldcZHiVblCIjWqf2L22WMAF+ACRDkTq8+ acrrepository.azurecr.io

      - name: Build and Push Docker image
        run: |
          docker build -t acrrepository.azurecr.io/dashboard:latest .
          docker push acrrepository.azurecr.io/dashboard:latest

          git clone https://github.com/sneha-dhande123/Calculator
          cd Calculator
          git checkout master
          git pull

          git config user.name sneha-dhande123
          git config user.email sneha789dhande@gmail.com

          yq e '.spec.template.spec.containers[0].image = "acrrepository.azurecr.io/dashboard:${{ env.GITHUB_BRANCH }}"' -i Deployment.yaml

          git add .
          git commit -m "Updating newer image"
          git push --set-upstream origin master
