name: Deploy to AKS Cluster
on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  production:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      

      - name: Build the Docker image And Pushing in GitOps
        run: |
          docker build -t acrrepository.azurecr.io/ .
          docker push yourACRName.azurecr.io

          git clone https://github.com/sneha-dhande123/Calculator.git
          cd Calculator
          git master
          
          git config user.name sneha-dhande123
          git config user.email sneha789dhande@gmail.com

          yq e '.spec.template.spec.containers[0].image = "acrrepository.azurecr.io/Calculator:${{ env.GITHUB_BRANCH }}"' -i Deployment.yaml

          git add .
          git commit -m "Updating newer image"
          git push --set-upstream origin master
