name: Deploy to AKS Cluster

on:
  push:
    branches:
      - master

jobs:
  production:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        run: docker login -u acrrepository -p D87PyhU8ipAeLEUolrwldcZHiVblCIjWqf2L22WMAF+ACRDkTq8+ acrrepository.azurecr.io

      - name: Build and Push Docker image
        run: |
          docker pull nginx:latest
          docker tag nginx:latest acrrepository.azurecr.io/dashboard:latest
          docker push acrrepository.azurecr.io/dashboard:latest
          
          git clone https://github.com/sneha-dhande123/Calculator
          cd Calculator
          git checkout master
          
        

          yq e '.spec.template.spec.containers[0].image = "acrrepository.azurecr.io/dashboard:latest"' -i Deployment.yaml

          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/dashboard

          git config --global url."https://github.com/".insteadOf "https://${{ secrets.GITHUB_TOKEN }}@github.com/"
          
          git config --global user.name "sneha-dhande123"
          git config --global user.email "sneha789dhande@gmail.com"
          
          
          git add .
          git commit -m "Updating newer image"
          git push --set-upstream origin master
