name: Deploy to AKS Cluster

on:
  push:
    branches:
      - master

jobs:
  production:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        run: docker login -u acrrepository -p D87PyhU8ipAeLEUolrwldcZHiVblCIjWqf2L22WMAF+ACRDkTq8+ acrrepository.azurecr.io

      - name: Build and Push Docker image
        run: |
          docker pull nginx:latest
          docker tag nginx:latest acrrepository.azurecr.io/dashboard:latest
          docker push acrrepository.azurecr.io/dashboard:latest

      - name: Update Kubernetes Deployment
        run: |
          git clone https://github.com/sneha-dhande123/Calculator
          cd Calculator
          git checkout master

          # Update the image in the Kubernetes deployment file
          yq e '.spec.template.spec.containers[0].image = "acrrepository.azurecr.io/dashboard:latest"' -i Deployment.yaml

          # Configure Git with the GitHub token
          git config --global user.name "sneha-dhande123"
          git config --global user.email "sneha789dhande@gmail.com"

          # Set the Git credentials directly
          git remote set-url origin https://sneha-dhande123:${{ secrets.GITHUB_TOKEN }}@github.com/sneha-dhande123/Calculator.git

          git add .
          git commit -m "Updating newer image"
          git push origin master
