name: Deploy to AKS Cluster
on:
  push:
    branches:
    #  - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  production:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Set env
        run: echo "GITHUB_BRANCH=$(echo $GITHUB_REF_NAME-$GITHUB_SHA)" >> $GITHUB_ENV

      - name: Build the Docker image And Pushing in GitOps
        run: |
          docker build -t yourACRName.azurecr.io/palettier-customer-ui:${{ github.sha }} .
          docker push yourACRName.azurecr.io/palettier-customer-ui:${{ github.sha }}

          git clone https://github.com/wohlig/palettier-gitops
          cd palettier-gitops
          git checkout production
          
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@wohlig.com"

          yq e '.spec.template.spec.containers[0].image = "yourACRName.azurecr.io/palettier-customer-ui:${{ env.GITHUB_BRANCH }}"' -i deployment.apps/palettier-customer-ui.yaml

          git add .
          git commit -m "Updating newer image"
          git push --set-upstream origin production
