name: Deploy to AKS Cluster

on:


  workflow_dispatch:
jobs:
  production:
    runs-on: ubuntu-latest
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  ACR_REGISTRY: acrrepository.azurecr.io
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Image Tag
        run: echo "IMAGE_TAG=$(date +'%Y%m%d')-$((GITHUB_RUN_NUMBER))" >> $GITHUB_ENV

      - name: Docker Login
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $ACR_REGISTRY

      - name: Build and Push Docker image
        run: |
          docker pull nginx:latest
          docker tag nginx:latest acrrepository.azurecr.io/dashboard:$IMAGE_TAG
          docker push acrrepository.azurecr.io/dashboard:$IMAGE_TAG

      - name: Update Kubernetes Deployment
        run: |
          git clone https://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@github.com/sneha-dhande123/Calculator
          cd Calculator
          git checkout master
          yq e '.spec.template.spec.containers[0].image = "acrrepository.azurecr.io/dashboard:$IMAGE_TAG"' -i Deployment.yaml
          
          git config --global user.name "sneha-dhande123"
          git config --global user.email "sneha789dhande@gmail.com"
          git add .
          git commit -m "Updating newer image with tag $IMAGE_TAG"
          git push origin master
        env:
          TOKEN: ${{ secrets.TOKEN }}
