name: Pushing Image to ACR

on:
  push:
    branches:
      - master

jobs:
  push-acr-3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Image Tag
        run: |
          CURRENT_DATE=$(date +'%Y%m%d')  # Get the current date in the format YYYY/MM/DD
          MAJOR_VERSION="10"                 # Set the major version to 10
          MINOR_VERSION=$((GITHUB_RUN_NUMBER / 1000))  # Calculate the minor version based on GITHUB_RUN_NUMBER
          PATCH_VERSION=$((GITHUB_RUN_NUMBER % 1000))  # Calculate the patch version based on GITHUB_RUN_NUMBER

          # Replace colons in the date with underscores
          CLEAN_DATE=$(echo $CURRENT_DATE | tr -d ':')

          IMAGE_TAG="${CLEAN_DATE}-v${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}"

          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "Generated IMAGE_TAG: $IMAGE_TAG"

      - name: Docker Login
        run: docker login -u acrrepository -p D87PyhU8ipAeLEUolrwldcZHiVblCIjWqf2L22WMAF+ACRDkTq8+ acrrepository.azurecr.io

      - name: Build and Push Docker image
        run: |
          docker pull nginx:latest
          docker tag nginx:latest acrrepository.azurecr.io/dashboard:$IMAGE_TAG
          docker push acrrepository.azurecr.io/dashboard:$IMAGE_TAG
